### ISSUE TITLE
Pass `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` to `cmake` in `clang-tidy` workflow

### ISSUE THREAD

**Issue by SwooshyCueb** [irods/irods_reusable_github_workflows#6]
We are moving away from setting `CMAKE_EXPORT_COMPILE_COMMANDS` in `CMakeLists.txt` files to allow builders to set it as needed on the command line. Therefore, `-DCMAKE_EXPORT_COMPILE_COMMANDS=ON` needs to be passed to `cmake` in the `clang-tidy` workflow here:
https://github.com/irods/irods_reusable_github_workflows/blob/b644ab25630ef6b102384f5d94c90f45728c2ef4/.github/workflows/linter-irods-clang-tidy.yml#L84

**Comment by korydraughn** [comment]
@SwooshyCueb Please close if complete.
